### PR TITLE
start fixing android back button problem by preventing it

### PR DESCRIPTION
**Pull request by dgobaud**
for https://mobius-network.atlassian.net/browse/MOB-478 came up with idea of disabling back button when it would close the app (not navigate back or close an in-app screen). this is better than getting stuck on reopen.

don't know much react native so wasn't able to finish figuring out how to get the current navigator state to see if it is at the top level. the navigators......

i know if showing if (navigators.Auth) { ... } its in the Auth one which only has 1 layer so definitely block it then

### CODE REVIEW

**Comment by dgobaud** [comment]
I think i figured out a better solution! this now works in the emulator based on comment here https://github.com/facebook/react-native/issues/13775

**Comment by dgobaud** [comment]
actually its weird - what this seems to do is on the first launch of the app after install, hit back button, its broken like before.

then kill the app, restart it, now hit back button, reopen app it works.

Don't understand what is going on... here is a video of it

[weird.mov.zip](https://github.com/mobius-network/wallet/files/2408940/weird.mov.zip)

**Comment by dgobaud** [comment]
[working.mov.zip](https://github.com/mobius-network/wallet/files/2408951/working.mov.zip)

**Comment by nebolsin** [comment]
@codefo let's check how it works on our testing devices

**Pull request merged**
